### ISSUE TITLE
SDK 7 build errors with Android Studio

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-Android#1834]
Please fill out the following details:

1. Version of Mobile SDK Used: 7
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: Windows (Android Studio)
4. Device: NA
5. Steps to reproduce: Create a new SDK 7 project and try to build it in Android Studio (import projcet function)
6. Actual behavior: Build fails with errors:

Error:(64, 34) error: package android.support.v4.content does not exist
Error:(297, 40) error: cannot find symbol variable FileProvider

This used to work fine with SDK 6.2

7. Expected Behavior: No errors
8. Error Log: NA

**Comment by bhariharan** [comment]
Seems to work fine for me.

Steps followed:
- `npm install forcehybrid`.
- `forcehybrid create`.
- Go through the steps to create a `hybrid_local` app, choosing `android` as the platform of choice.
- In `Android Studio`:
    - File -> New -> Import Project -> Navigate to `<app folder>/platforms/android` -> Open.
    - Wait for `Gradle` sync to complete and the workspace to settle down.
    - Run `app` from within `Android Studio`.
- The app runs successfully and loads the login page in an emulator.

You might want to invalidate your `Android Studio` cache and try again. This error typically indicates some dependency on an older version of `Android Support Library`. With `Mobile SDK 7.0`, you will need to use the `AndroidX` or `Jetpack` equivalent libraries.

**Comment by alsocalledchris** [comment]
Thanks @bhariharan  for your quick response. Yes - I think the issue is in cordova camera plugin that is being used.

**Comment by bhariharan** [comment]
Maybe raise an issue with the camera plugin to support `Android Studio 3.x` and `Jetpack`?
