### ISSUE TITLE
FirebaseInstanceId is deprecated

### ISSUE THREAD

**Issue by rsmilne** [forcedotcom/SalesforceMobileSDK-Android#2323]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.0.0
2. Issue found in Native App or Hybrid App: Hybrid app
3. OS Version: Android 12
4. Device: Samsung S21 Ultra

The SDK uses FirebaseInstanceId to support firebase push notifications.  FirebaseInstanceId is deprecated.  I was able to get it to work with gradle 3.4.2 but when updating gradle which at this point is necessary and recommended in most of the Salesforce example projects available firebase no longer works due to the use of this deprecated class.  It shows FATAL EXCEPTION.

"Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId"

https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId

Thanks!

**Comment by gkotula** [comment]
Hi @rsmilne, I just used `forcehybrid` to create a new Hybrid app based on the latest Mobile SDK version, and Firebase Cloud Messaging registration happened successfully upon login utilizing the `FirebaseInstanceId` API.  Could you try updating to the latest Mobile SDK version and see if that fixes the issue for you?

We are aware of the deprecation and it is on our roadmap to migrate to the newer APIs, but hopefully the latest SDK version can unblock you.

**Comment by wmathurin** [comment]
We are upgrading to firebase messaging 23.1.1 in our next version of Mobile SDK (version 11.0).
The changes are already in dev. See https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2380

**Comment by rsmilne** [comment]
Hi, how is this closed when the fix was rolled back?  Both dev as version 11.0.0 are still using deprecated FirebaseInstanceId (https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId)

**Comment by wmathurin** [comment]
Indeed we had to revert the changes for internal reasons. So re-opening the issue for now.

**Comment by rsmilne** [comment]
Now that the graldle version was updated in version 11.0.0 push notifications don't work since FirebaseInstanceId required a lower version of gradle.  Is there any workaround to get push notifications working?

**Comment by brandonpage** [comment]
@rsmilne What do you mean?  We shipped Mobile SDK 11.0 with gradle 7.4.2, which works with our existing Firebase configuration.

**Comment by rsmilne** [comment]
You are correct sorry.  It does work if you force the firebaseVersion to 20.1.0.   This is for a react-native project. I was using other complementary libraries like react-push-notifications or react-native-notifications which if updated conflicted with the deprecated FirebaseInstanceId.  I was able to work around that as well as add the changes to support sdkVersion 33 which was also part of my issue.  Thanks for the quick response!

**Comment by wmathurin** [comment]
Upgrade Firebase Messaging to 23.3.1 coming in MSDK 12.0. See https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2486
